In [584]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [585]:
dataset1 = pd.read_csv('train_u6lujuX_CVtuZ9i.csv')
dataset1.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

# Presprocessing of Dataset

In [586]:
dataset1.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [587]:
# fill the missing values using pandas
dataset1['LoanAmount'] = dataset1['LoanAmount'].fillna(dataset1['LoanAmount'].mean())
dataset1['Loan_Amount_Term'] = dataset1['Loan_Amount_Term'].fillna(dataset1['Loan_Amount_Term'].mean())
dataset1['Credit_History'] = dataset1['Credit_History'].fillna(dataset1['Credit_History'].mean())

In [588]:
dataset1.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [589]:
# fill the categorical missing data
dataset1['Gender'] = dataset1['Gender'].fillna(dataset1['Gender'].mode()[0])
dataset1['Married'] = dataset1['Married'].fillna(dataset1['Married'].mode()[0])
dataset1['Dependents'] = dataset1['Dependents'].fillna(dataset1['Dependents'].mode()[0])
dataset1['Self_Employed'] = dataset1['Self_Employed'].fillna(dataset1['Self_Employed'].mode()[0])

In [590]:
dataset1.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [591]:
dataset1

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0  146.412162             360.0   
1               4583             1508.0  128.000000             360.0   
2               3000                0.0   66.000000             360.0   
3               2583             2358.0  120.000000             360.0   
4               6000                0.0  141.000000             360.0   
..               ...                ...         ...               ...   
609             2900                0.0   71.000000             360.0   
610             4106                0.0   40.000000             180.0   
611             8072              240.0  253.000000             360.0   
612             7583                0.0  187.000000             360.0   
613             4583                0.0  133.000000             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [592]:
# removing unnecessary data
column = ['Loan_ID', 'CoapplicantIncome', 'Dependents']
dataset1 = dataset1.drop(columns = column, axis = 1)
dataset1.head()

Gender Married     Education Self_Employed  ApplicantIncome  LoanAmount  \
0   Male      No      Graduate            No             5849  146.412162   
1   Male     Yes      Graduate            No             4583  128.000000   
2   Male     Yes      Graduate           Yes             3000   66.000000   
3   Male     Yes  Not Graduate            No             2583  120.000000   
4   Male      No      Graduate            No             6000  141.000000   

   Loan_Amount_Term  Credit_History Property_Area Loan_Status  
0             360.0             1.0         Urban           Y  
1             360.0             1.0         Rural           N  
2             360.0             1.0         Urban           Y  
3             360.0             1.0         Urban           Y  
4             360.0             1.0         Urban           Y

In [593]:
X = dataset1.iloc[:, :-1].values
y = dataset1.iloc[:, -1].values

In [594]:
X

array([['Male', 'No', 'Graduate', ..., 360.0, 1.0, 'Urban'],
       ['Male', 'Yes', 'Graduate', ..., 360.0, 1.0, 'Rural'],
       ['Male', 'Yes', 'Graduate', ..., 360.0, 1.0, 'Urban'],
       ...,
       ['Male', 'Yes', 'Graduate', ..., 360.0, 1.0, 'Urban'],
       ['Male', 'Yes', 'Graduate', ..., 360.0, 1.0, 'Urban'],
       ['Female', 'No', 'Graduate', ..., 360.0, 0.0, 'Semiurban']],
      dtype=object)

In [595]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0, 1, 2, 3, 8])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [596]:
print(X)

[[0.0 1.0 1.0 ... 146.41216216216216 360.0 1.0]
 [0.0 1.0 0.0 ... 128.0 360.0 1.0]
 [0.0 1.0 0.0 ... 66.0 360.0 1.0]
 ...
 [0.0 1.0 0.0 ... 253.0 360.0 1.0]
 [0.0 1.0 0.0 ... 187.0 360.0 1.0]
 [1.0 0.0 1.0 ... 133.0 360.0 0.0]]


In [597]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [598]:
y = y.reshape(len(y),1)
print(y)

[[1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]


In [599]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [600]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [601]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=3)
A = np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)
print(A)

[[0. 1.]
 [1. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [0. 0.]
 [0. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [0. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [0. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [1. 1.]
 [0. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [1. 0.]
 [1. 1.]
 [0. 0.]
 [0. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 0.]
 [0. 1.]
 

# Test dataset

In [602]:
dataset2 = pd.read_csv('test_Y3wMUE5_7gLdaTN.csv')

In [603]:
# fill the missing values using pandas
dataset2['LoanAmount'] = dataset2['LoanAmount'].fillna(dataset2['LoanAmount'].mean())
dataset2['Loan_Amount_Term'] = dataset2['Loan_Amount_Term'].fillna(dataset2['Loan_Amount_Term'].mean())
dataset2['Credit_History'] = dataset2['Credit_History'].fillna(dataset2['Credit_History'].mean())

In [604]:
# fill the categorical missing data
dataset2['Gender'] = dataset2['Gender'].fillna(dataset2['Gender'].mode()[0])
dataset2['Married'] = dataset2['Married'].fillna(dataset2['Married'].mode()[0])
dataset2['Self_Employed'] = dataset2['Self_Employed'].fillna(dataset2['Self_Employed'].mode()[0])
dataset2['Dependents'] = dataset2['Dependents'].fillna(dataset2['Dependents'].mode()[0])

In [605]:
column = ['Loan_ID','CoapplicantIncome', 'Dependents']
dataset2 = dataset2.drop(columns = column, axis = 1)
print(dataset2)

    Gender Married     Education Self_Employed  ApplicantIncome  LoanAmount  \
0     Male     Yes      Graduate            No             5720       110.0   
1     Male     Yes      Graduate            No             3076       126.0   
2     Male     Yes      Graduate            No             5000       208.0   
3     Male     Yes      Graduate            No             2340       100.0   
4     Male      No  Not Graduate            No             3276        78.0   
..     ...     ...           ...           ...              ...         ...   
362   Male     Yes  Not Graduate           Yes             4009       113.0   
363   Male     Yes      Graduate            No             4158       115.0   
364   Male      No      Graduate            No             3250       126.0   
365   Male     Yes      Graduate            No             5000       158.0   
366   Male      No      Graduate           Yes             9200        98.0   

     Loan_Amount_Term  Credit_History Property_Area

In [606]:
dataset1.isnull().sum()

Gender              0
Married             0
Education           0
Self_Employed       0
ApplicantIncome     0
LoanAmount          0
Loan_Amount_Term    0
Credit_History      0
Property_Area       0
Loan_Status         0
dtype: int64

In [607]:
dataset2.head()

Gender Married     Education Self_Employed  ApplicantIncome  LoanAmount  \
0   Male     Yes      Graduate            No             5720       110.0   
1   Male     Yes      Graduate            No             3076       126.0   
2   Male     Yes      Graduate            No             5000       208.0   
3   Male     Yes      Graduate            No             2340       100.0   
4   Male      No  Not Graduate            No             3276        78.0   

   Loan_Amount_Term  Credit_History Property_Area  
0             360.0        1.000000         Urban  
1             360.0        1.000000         Urban  
2             360.0        1.000000         Urban  
3             360.0        0.825444         Urban  
4             360.0        1.000000         Urban

In [608]:
X_find = dataset2.iloc[:, :].values
print(X_find)

[['Male' 'Yes' 'Graduate' ... 360.0 1.0 'Urban']
 ['Male' 'Yes' 'Graduate' ... 360.0 1.0 'Urban']
 ['Male' 'Yes' 'Graduate' ... 360.0 1.0 'Urban']
 ...
 ['Male' 'No' 'Graduate' ... 360.0 0.8254437869822485 'Semiurban']
 ['Male' 'Yes' 'Graduate' ... 360.0 1.0 'Rural']
 ['Male' 'No' 'Graduate' ... 180.0 1.0 'Rural']]


In [609]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0, 1, 2, 3, 8])], remainder='passthrough')
X_find = np.array(ct.fit_transform(X_find))

In [610]:
print(X_find)

[[0.0 1.0 0.0 ... 110.0 360.0 1.0]
 [0.0 1.0 0.0 ... 126.0 360.0 1.0]
 [0.0 1.0 0.0 ... 208.0 360.0 1.0]
 ...
 [0.0 1.0 1.0 ... 126.0 360.0 0.8254437869822485]
 [0.0 1.0 0.0 ... 158.0 360.0 1.0]
 [0.0 1.0 1.0 ... 98.0 180.0 1.0]]


In [611]:
regressor.predict(X_find[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

array([1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0.])